// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTxnHInNPaGsBjkw0lOjnC10rLb_OrwJ8',
    appId: '1:98322273582:web:8c37679e4598b224c4d6bf',
    messagingSenderId: '98322273582',
    projectId: 'clubzserver',
    authDomain: 'clubzserver.firebaseapp.com',
    storageBucket: 'clubzserver.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD8BuQIYRkYMiVPU1O93kTkrtQVTotC7E',
    appId: '1:98322273582:android:a02ca65dcbb23514c4d6bf',
    messagingSenderId: '98322273582',
    projectId: 'clubzserver',
    storageBucket: 'clubzserver.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-vcFuyIMmReQZ6S2Vc86yFfC3VKaK-RI',
    appId: '1:98322273582:ios:516e6d72dbc659dbc4d6bf',
    messagingSenderId: '98322273582',
    projectId: 'clubzserver',
    storageBucket: 'clubzserver.appspot.com',
    iosClientId: '98322273582-kjnln8mcgt1m8hpnauts2n2vt3s0duq5.apps.googleusercontent.com',
    iosBundleId: 'com.example.clubz',
  );
}
